services:
  monitor:
    build: .
    container_name: m3u-monitor
    ports:
      - "2029:2029"
    volumes:
      - /data/docker/m3u-monitor-config:/app/data
    environment:
      - TEST_RATE=28800      # Sets the check interval to 1,800 seconds (30 minutes).
      - PORT=2029           # Sets the port the application runs on Must match the container port.
      - FFPROBE_TIMEOUT=30  # Sets the timeout for each stream check.
      - TZ=US/Chicago     # Timezone
    restart: always
